/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hUpK17QgpV8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Work_Sans } from 'next/font/google'
import { Chivo } from 'next/font/google'

work_sans({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Separator } from "@/components/ui/separator"

export function Component() {
  return (
    (<div className="flex flex-col min-h-screen">
      <header
        className="bg-background border-b px-4 md:px-6 py-3 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <BookIcon className="w-6 h-6 text-primary" />
          <span className="font-semibold text-lg">Digital Book</span>
        </Link>
        <div className="flex items-center gap-4">
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Read
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Manage
          </Link>
          <Button size="sm">Start Reading</Button>
        </div>
      </header>
      <main className="flex-1 bg-background">
        <div className="max-w-3xl mx-auto py-12 px-4 md:px-0">
          <div className="prose prose-neutral">
            <h1>The Minimalist's Guide to a Clutter-Free Life</h1>
            <p>
              In this digital book, we'll explore the principles of minimalism and how to apply them to your everyday
              life. From decluttering your home to simplifying your schedule, you'll learn practical tips and strategies
              to live a more intentional and fulfilling life.
            </p>
            <p>Get ready to discover the freedom and joy that comes with embracing a minimalist lifestyle.</p>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Avatar className="w-8 h-8">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-medium">John Doe</div>
                  <div className="text-sm text-muted-foreground">Author</div>
                </div>
              </div>
              <div className="flex items-center gap-2 text-muted-foreground">
                <ClockIcon className="w-4 h-4" />
                <span>15 min read</span>
              </div>
            </div>
            <Separator className="my-8" />
            <div className="prose prose-neutral">
              <h2>Chapter 1: Decluttering Your Home</h2>
              <p>
                The first step to a minimalist lifestyle is to declutter your living space. In this chapter, you'll
                learn practical strategies for identifying and removing unnecessary items from your home.
              </p>
              <h3>Sorting and Categorizing</h3>
              <p>
                Begin by going through each room and sorting your belongings into categories. This will help you
                identify what you truly need and what can be donated or discarded.
              </p>
              <h3>The 30-Day Challenge</h3>
              <p>
                Try the 30-day challenge, where you remove one item on the first day, two items on the second day, and
                so on. This gradual approach can make the decluttering process more manageable.
              </p>
              <h2>Chapter 2: Simplifying Your Schedule</h2>
              <p>
                In addition to decluttering your physical space, it's important to simplify your schedule and focus on
                the activities that truly matter to you.
              </p>
              <h3>Prioritizing Your Time</h3>
              <p>
                Identify the tasks and commitments that are essential to your well-being and happiness, and learn to say
                no to everything else.
              </p>
              <h3>Batch Your Tasks</h3>
              <p>Group similar tasks together to increase efficiency and minimize distractions.</p>
            </div>
          </div>
        </div>
      </main>
      <footer
        className="bg-muted border-t px-4 md:px-6 py-6 text-center text-sm text-muted-foreground">
        &copy; 2024 Digital Book. All rights reserved.
      </footer>
    </div>)
  );
}

function BookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>)
  );
}


function ClockIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
